version: 2
updates:
  - package-ecosystem: gomod
    directory: /influxdb_mcp
    schedule:
      interval: weekly
  - package-ecosystem: docker
    directory: /influxdb_mcp
    schedule:
      interval: weekly
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
